<h1>Stockage de Produit </h1>
<form id="form1" method="post">
	<table>
		<tr><th>N°</th><th>Date de Stock</th><th>Quantité</th></tr>
		<?php 
			//Listes des Stock d'un produit
			foreach($this->viewData['listStock'] as $stock)
				echo '<tr><td>'.$stock['id'].'</td><td>'.$stock['date'].'</td>
					<td>'.$stock['quantite'].'</td></tr>';

		?>
		<tr>
			<td>Nouveau Stock</td>
			<td>
				<input type="text" id='date' name='date' 
				value="<?php echo $this->viewData['stock']->getDate();?>"/>
				<br>
				<span id="erreur">
					<?php echo $this->viewData['stock']->ValidationMessage("date");?>
				</span>
			</td>
			<td>
				<input type="text" id='quantite' name='quantite' 
					value="<?php echo $this->viewData['stock']->getQuantite();?>"/>
				<br>
				<span id="erreur">
					<?php echo $this->viewData['stock']->ValidationMessage("quantite");?>
				</span>
			</td>
		</tr>
		<tr><td colspan='3'><input type="submit" value="Ajouter au Stock" /></td></tr>
	</table>
	<a href="?controler=Produit">Retour</a>
</form>