<h1>Supprimer un produit</h1>

<form id="form1" method="post">
	<table>
		<tr>
			<td>Id : </td>
			<td><input type="text" id="id" name="id" readonly="true" 
					value="<?php echo $this->viewData['produit']->getId();?>"/>
			</td>
		</tr>
		<tr>
			<td>Designation : </td>
			<td>
			<input type="text" id="designation" name="designation" readonly="true" 
				value="<?php echo $this->viewData['produit']->getDesignation();?>"/>
			</td>
		</tr>
		<tr>
			<td>Prix Unitaire : </td>
			<td>
				<input type="text" id="prix" readonly="true" name="prix" 
				value="<?php echo $this->viewData['produit']->getPrixUnitaire();?>"/>(DH)
			</td>
		</tr>
		<tr>
			<td>Tva : </td>
			<td>
				<input type="text" id="tva" readonly="true" name="tva" 
				value="<?php echo $this->viewData['produit']->getTva();?>"/>(%)
			</td>
		</tr>
		<tr>
			<td>Quantité : </td>
			<td>
				<input type="text" id="quantite" readonly="true" name="quantite" 
				value="<?php echo $this->viewData['produit']->getQuantite();?>"/>
			</td>
		</tr>
		<tr>
			<td>Famille : </td>
			<td>
				<input type="text" id="famille" readonly="true" name="famille" 
				value="<?php
					foreach($this->viewData['listFamille'] as $cat)
						if($cat['id'] == $this->viewData['produit']->getIdFamille())
								echo $cat['famille'];
				?>"/>
			</td>
		</tr>
		<tr><td colspan='2'><input type="submit" value= "  Supprimer  " /></td></tr>
	</table>
</form>
<a href="?controler=Produit">Retour</a>